import{DEVICES,VOCABS,presetGeometry,mergeOpenings}from"./geometry.js";import{detectCells}from"./detect.js";import{stlBlob}from"./stl-export.js";const $=x=>document.getElementById(x),ns="http://www.w3.org/2000/svg";let imageData=null,imageFile=null,g,selected=new Set(),custom=false;Object.keys(DEVICES).forEach(k=>$("device").add(new Option(k,k)));Object.keys(VOCABS).forEach(k=>$("vocab").add(new Option(k,k)));
function reset(){g=presetGeometry($("device").value,$("vocab").value,+$("wall").value,+$("radius").value);custom=false;selected.clear();if($("largeCell").checked){let s=(+$("mergeStart").value||1)-1,n=+$("mergeSpan").value||4,ids=g.openings.filter(o=>o.row===0&&o.col>=s&&o.col<s+n).map(o=>o.id);g.openings=mergeOpenings(g.openings,ids,+$("radius").value)}render()}
function render(){let s=$("preview");s.setAttribute("viewBox",`0 0 ${g.d.width} ${g.d.height}`);s.innerHTML="";if(imageData){let im=document.createElementNS(ns,"image");Object.entries({href:imageData,x:+$("imgX").value||0,y:+$("imgY").value||0,width:+$("imgW").value||g.d.width,height:+$("imgH").value||g.d.height,opacity:+$("opacity").value,preserveAspectRatio:"none"}).forEach(([k,v])=>im.setAttribute(k,v));s.append(im)}let plate=document.createElementNS(ns,"rect");Object.entries({x:0,y:0,width:g.d.width,height:g.d.height,fill:imageData?"rgba(215,220,224,.38)":"#d7dce0",stroke:"#263238","stroke-width":".45"}).forEach(([k,v])=>plate.setAttribute(k,v));s.append(plate);for(let o of g.openings){let r=document.createElementNS(ns,"rect");r.classList.add("opening");if(selected.has(o.id))r.classList.add("selected");if(!o.enabled)r.classList.add("disabled");Object.entries({x:o.x,y:o.y,width:o.w,height:o.h,rx:o.r,fill:"white",stroke:"#263238","stroke-width":".3"}).forEach(([k,v])=>r.setAttribute(k,v));r.onclick=e=>{if(!e.shiftKey)selected.clear();selected.has(o.id)?selected.delete(o.id):selected.add(o.id);render()};r.ondblclick=()=>{o.enabled=!o.enabled;render()};s.append(r)}$("stats").textContent=`${g.openings.filter(o=>o.enabled).length} openings • ${g.d.width} × ${g.d.height} × ${+$("thickness").value} mm`}
function dl(blob,name){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
["device","vocab","wall","radius","largeCell","mergeStart","mergeSpan"].forEach(id=>$(id).onchange=reset);["opacity","imgX","imgY","imgW","imgH"].forEach(id=>$(id).oninput=()=>render());
$("device").addEventListener("change",()=>{let d=DEVICES[$("device").value];$("imgW").value=d.width;$("imgH").value=d.height});
$("imageUpload").onchange=e=>{imageFile=e.target.files[0]||null;if(!imageFile){imageData=null;render();return}let r=new FileReader();r.onload=()=>{imageData=r.result;render()};r.readAsDataURL(imageFile)};
$("detect").onclick=async()=>{if(!imageFile){$("status").textContent="Choose an image first.";return}$("status").textContent="Detecting…";let O=await detectCells(imageFile,g.d,+$("threshold").value,+$("minCell").value);if(O.length){g.openings=O;custom=true;selected.clear();$("status").textContent=`Detected ${O.length} candidate cells — review before export.`;render()}else $("status").textContent="No reliable grid found. Try another threshold or edit the preset."};
$("mergeSelected").onclick=()=>{g.openings=mergeOpenings(g.openings,[...selected],+$("radius").value);selected.clear();custom=true;render()};$("resetGrid").onclick=reset;$("stl").onclick=()=>dl(stlBlob(g,+$("thickness").value),"keyguard.stl");
$("svgBtn").onclick=()=>{let c=$("preview").cloneNode(true),im=c.querySelector("image");if(im)im.remove();c.setAttribute("xmlns",ns);c.setAttribute("width",g.d.width+"mm");c.setAttribute("height",g.d.height+"mm");dl(new Blob([new XMLSerializer().serializeToString(c)],{type:"image/svg+xml"}),"keyguard.svg")};reset();